name: ConterSubsHelper
version: '${project.version}'
main: dev.sasukector.contersubshelper.ConterSubsHelper
api-version: 1.18
authors: [ Sasukector ]
description: This is the core plugin for ConterSubsHelper
website: https://sasukector.dev
commands:
  played:
    description: Command to see played time of a player
    usage: /played [playerName]
  sit:
    description: Command to sit
    usage: /sit